######################################################################
# Automatically generated by qmake (2.01a) Wed Jan 18 12:07:16 2017
######################################################################

TEMPLATE = app
TARGET = hello
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += hello.cc
